# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JQIaNC0WxRcSqAK60UO4JloYIgB1X9sT
"""

import pandas as pd
import numpy as np

serie1 = pd.Series([10, 9, 8, 2, 5])
serie1

serie1.values

serie1.index

serie22 = pd.Series(np.random.rand(10), index=np.arange(1,11))
serie22

serie2 = pd.Series([4, 7, 6, 3]), index=['a','b','c','d']
serie2

serie2 = pd.Series([True, 7, 6, 3]), index=[4.5, 'b','c','d']



capitais = {
    'Pernambuco': 'Recife',
    'Paraíba': 'João Pessoa',
    'Ceará':'Fortaleza',
    'Bahia': 'Salvador',
    'Alagoas': 'Maceió'
}

type(capitais)

serire3 = pd.Series(capitais)
serire3

type(serire3)

dictEmpresas = {
    'Apple': 947.062,
    'Google': 819.573,
    'Amazon': 705.646,
    'Microsoft': 611.460,
    'Tencent': 214.023,
    'McDonalds': 194.526,
    'Visa': 191.032,
    'Facebook': 186.421,
    'Alibaba': 169.966,
    'Louis Vultton': 124.273
}

serie4 = pd.Series(dictEmpresas)
serie4

empresas = ['Apple','Google','Amazon','Microsoft','Tencent', 'McDonalds', 'Visa', 'Facebook', 'Alibaba', 'Louis Vultton']





bilhoes = [
    947.062,
    819.573,
    705.646,
    611.460,
    214.023,
    194.526,
    191.032,
    186.421,
    169.966,
    124.273
]

serie5 = pd.Series(bilhoes, index=empresas)
serie5

import matplotlib.pyplot as plt

serie5.plot()

